### ISSUE TITLE
The get_average_attention() function do not used in the implement? 

### ISSUE THREAD

**Issue by Suho0922** [google/break-a-scene#6]
https://github.com/google/break-a-scene/blob/9cac7d3fed4bc3cd64fba5a0a12f3b39a40c30f5/train.py#L1393C6-L1394

**Comment by omriav** [comment]
Hi,
Sorry, but I do not understand the question.
The function `aggregate_attention` that is using the function `get_average_attention` is being used [here](https://github.com/google/break-a-scene/blob/9cac7d3fed4bc3cd64fba5a0a12f3b39a40c30f5/train.py#L1190).

**Comment by Suho0922** [comment]
attention_maps = self.get_average_attention()
        attention_maps = self.controller.attention_store

I mean in here [https://github.com/google/break-a-scene/blob/9cac7d3fed4bc3cd64fba5a0a12f3b39a40c30f5/train.py#L1393C6-L1394](url) attention_maps is assigned with return value of get_average_attention function however the controller.attention_store value is assigned to attention_maps right after. So I am curious about what is get_average_attention doing. It seems do not modify any variable in instance. Thank you for reply!

**Comment by omriav** [comment]
Hi,
Thank you very much for spotting this bug!
Because I reset the attention store at each iteration [here](https://github.com/google/break-a-scene/blob/135cd4a40e117efb80175db7ca5c0ea44e514ca8/train.py#L1231), there was no need for aggregation during the training process.
However, for visualizing the aggregated attention map over the entire diffusion process, there is a need for this aggregation.
I fixed it.

**Comment by Suho0922** [comment]
Aha! because in training process we just denosing in single random sampled time step, however in inference we want to see the aggregated attention map of during whole denoising timesteps. Thanks a lot!

**Comment by omriav** [comment]
You're welcome.
